#!/bin/bash
#run runtime comparisons
diff inputstoc_opt1.txt inputstoc_opt2.txt
rm out*

cp inputstoc_opt1.txt inputstoc.txt
./astochastic > out1.log
./astochastic > out2.log

cp inputstoc_opt2.txt inputstoc.txt
./astochastic > out3.log
./astochastic > out4.log
./astochastic > out5.log

cat out1.log out2.log out3.log out4.log out5.log > out.log

egrep 'radMC      :|radWood    :| Transport: radtrans' out.log

#run Workaround 1 problem, 3.2, resolve!
cp inputstoc_3.2.txt inputstoc.txt
./astochastic > out3.2.log

#run Workaround 2 problem, 9.3, resolve!
cp inputstoc_9.3.txt inputstoc.txt
./astochastic > out9.3.log

cp inputstoc_9.3_2.txt inputstoc.txt
./astochastic > out9.3_2.log
